
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "John Doe",
    "username": "johndoe77",
    "password": "password",
    "isAdmin": "false"
}

###
GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY1MGI3YTEyNDQzYzAyM2FlNGQ0MjM0MSIsIm5hbWUiOiJKb2huIERvZSIsInVzZXJuYW1lIjoiam9obmRvZTY2IiwicGFzc3dvcmQiOiIkMmEkMTAkUGdvdlBvQUpHMnZLSXdLd0NJL0RYdTlDeEZ3d0xUWTZENG1iL0Y0NUk4MXF3a0pvbjNHcksiLCJpc0FkbWluIjpmYWxzZSwiX192IjowfSwiaWF0IjoxNjk1MjUxMDIwLCJleHAiOjE2OTUyNTQ2MjB9.eXPj4YSl4PNdK-OtRBbmVoczbTXiDOfRDlKb802LDtY
###
POST http://localhost:3000/api/sign-up
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "username": "johndoe66",
    "password": "testing12345",
    "passwordConfirm": "testing12345"
}

###
POST http://localhost:3000/api/sign-in
Content-Type: application/json

{
    "username": "johndoe66",
    "password": "testing12345"
}