
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "John Doe",
    "username": "johndoe77",
    "password": "password",
    "isAdmin": "false"
}

###
GET http://localhost:3000/api/users